package com.example.util

object AppStrings {

    fun get(key: String, lang: String): String {
        val map = when (lang.lowercase()) {
            "sr" -> sr
            "hr" -> hr
            "en" -> en
            else -> bs
        }
        return map[key] ?: bs[key] ?: key
    }

    private val bs = mapOf(
        "app_title" to "Peletko",
        "home" to "Početna",
        "back" to "Nazad",
        "refresh_temps" to "Osvježi temperature",
        "daily_entry_btn" to "Unos dnevne potrošnje",
        "daily_entry_sub" to "Brzi dnevni unos",
        "history_stats_btn" to "Istorija / Statistika",
        "history_stats_sub" to "Metrike (kg/m², kg/kW, troškovi) i trendovi",
        "purchase_btn" to "Magacin/Kupovina",
        "purchase_sub" to "+ Nova nabavka",
        "inventory_title" to "Stanje zaliha",
        "remaining_bags" to "Preostalo: %s",
        "remaining_kg" to "Preostalo: %s kg",
        "days_left" to "Dovoljno za ~%s dana",
        "stock_depleted" to "Zalihe potrošene",
        "low_stock" to "Nisko!",
        "today_entered" to "Danas uneseno",
        "today_not_entered" to "Danas još nije uneseno",
        "today_prompt" to "Kliknite za brzi unos današnje potrošnje",
        "history_tab" to "Istorija",
        "stats_tab" to "Detaljna statistika",
        "save" to "Sačuvaj",
        "save_daily" to "Spasi dnevni unos",
        "update_daily" to "Ažuriraj potrošnju",
        "bags" to "vreća",
        "bags_plural" to "vreće",
        "total_mass" to "Ukupna masa",
        "total_cost" to "Trošak",
        "outside_temp" to "Vanjska temperatura (°C)",
        "weather_auto_fetched" to "Automatski preuzeto s interneta",
        "weather_fetching" to "Dohvatanje temperature s interneta...",
        "notes" to "Kratka bilješka (opcionalno)",
        "stock_negative_title" to "Nema dovoljno peleta na stanju",
        "stock_negative_msg" to "Ovaj unos prelazi trenutno stanje magacina. Preostalo bi bilo u minusu. Želite li ipak snimiti unos?",
        "allow_negative_confirm" to "Dozvoli minus i spasi",
        "cancel" to "Otkaži",
        "delete" to "Obriši",
        "settings" to "Postavke",
        "heating_area" to "Površina objekta (m²)",
        "boiler_power" to "Snaga peći (kW)",
        "insulation" to "Izolacija objekta",
        "city" to "Grad / Klima zona",
        "brand" to "Proizvođač peleta",
        "theme" to "Tema aplikacije",
        "theme_system" to "Sistem",
        "theme_light" to "Svijetla",
        "theme_dark" to "Tamna",
        "language" to "Jezik aplikacije",
        "currency" to "Valuta (Prikaz troškova)",
        "auto_weather_setting" to "Automatski preuzmi vremensku prognozu",
        "saved" to "Snimljeno",
        "updated" to "Ažurirano",
        "deleted" to "Obrisano",
        "purchase_saved" to "Zalihe uvećane",
        "kg_per_m2" to "kg / m² sezona",
        "kg_per_kw" to "kg / kW peći",
        "cost_per_m2" to "po m²",
        "cost_per_day" to "po danu",
        "temp_vs_consumption" to "Prosječna temperatura/potrošnja peleta",
        "monthly_review" to "Mjesečni pregled potrošnje",
        "total_recorded" to "Ukupno evidentirano",
        "no_entries_yet" to "Još nema unosa potrošnje",
        "no_entries_sub" to "Započnite dnevni unos klikom na početnom ekranu.",
        "delete_entry_confirm" to "Da li ste sigurni da želite obrisati unos za datum %s (%s)?",
        "property_label" to "Objekat",
        "insulation_label" to "Izolacija",
        "kpi_title" to "Detalji o potrošnji",
        "specific_consumption" to "Specifična potrošnja",
        "boiler_load" to "Opterećenje snage",
        "cost_by_area" to "Trošak po površini",
        "daily_average" to "Dnevni prosjek",
        "unit_per_day" to "dan",
        "unit_per_day_short" to "vr/dan",
        "sample_days_short" to "d.",
        "days_count_short" to "dana unosa",
        "temp_correlation_title" to "Korelacija grijanja i temperature",
        "no_data" to "Nema podataka",
        "temp_correlation_tip" to "💡 Savjet: Uključeno automatsko preuzimanje temperature omogućava preciznu korelaciju bez ručnog unosa.",
        "no_monthly_data" to "Nema podataka za mjesečni pregled.",
        "stock_overview" to "Pregled zaliha",
        "one_pallet_rule" to "1 paleta = 70 vreća",
        "remaining" to "Preostalo",
        "total_purchased" to "Ukupno kupljeno",
        "purchases_history" to "Istorija nabavki",
        "no_purchases" to "Nema unesenih nabavki",
        "add_purchase_prompt" to "Dodajte kupovinu peleta klikom na dugme ispod.",
        "pallets" to "paleta",
        "delete_purchase_confirm" to "Da li ste sigurni da želite obrisati nabavku od %s paleta (%s)? Zalihe će biti umanjene.",
        "edit_purchase" to "Izmjena nabavke",
        "edit" to "Izmijeni",
        "purchase_updated" to "Nabavka ažurirana",
        "purchase_sheet_title" to "Unos nabavke u magacin",
        "purchase_sheet_info" to "1 paleta = tona = 70 vreća (1050 kg). Unosom paleta automatski se računa broj vreća i obrnuto.",
        "season" to "Sezona",
        "num_pallets" to "Broj paleta",
        "exact_bags" to "Tačan br. vreća",
        "price_per_pallet" to "Cijena po paleti",
        "quantity" to "Količina",
        "supplier" to "Dobavljač / Proizvođač",
        "settings_sec1" to "Izgled i Lokalizacija",
        "settings_sec2" to "Lokacija i Pelet",
        "settings_sec3" to "Snaga peći i grejna površina",
        "settings_sec4" to "Magacin i Nabavke",
        "pellet_class" to "Klasa peleta",
        "default_pallet_price" to "Podrazumijevana cijena palete",
        "allow_negative_title" to "Dozvoli unos kad nema zaliha",
        "allow_negative_sub" to "Upozori prije ulaska u negativno stanje",
        "about_app" to "O aplikaciji",
        "developer" to "Developer",
        "developer_name" to "ProleApps",
        "app_version" to "Verzija 1.2.0",
        "app_description" to "Jednostavno i precizno praćenje potrošnje peleta, stanja zaliha u magacinu i troškova grijanja uz automatsku vremensku prognozu.",
        "auto_temp_placeholder" to "Automatska temperatura...",
        "locked_temp_field" to "Zaključano polje (automatska temperatura)",
        "notes_placeholder" to "Npr. grijano 12 sati, vjetrovito...",
        "supplier_placeholder" to "Npr. Kovan, Šišarka, Ensa, Medex...",
        "step_x_of_y" to "Korak %d od %d",
        "next" to "Dalje",
        "start_tracking" to "Započni praćenje",
        "initial_setup" to "Osnovno podešavanje",
        "onboarding_step1_title" to "Jezik, valuta i grad",
        "onboarding_step1_sub" to "Podesite jezik sučelja, valutu za obračun troškova i vaš grad za automatsko preuzimanje temperatura.",
        "onboarding_step2_title" to "Snaga i kvadratura",
        "onboarding_step2_sub" to "Unesite snagu peći, grejnu površinu i izolaciju objekta za precizne industrijske proračune.",
        "onboarding_step3_title" to "Stanje magacina",
        "onboarding_step3_sub" to "1 paleta = 70 vreća (1050 kg). Unosom paleta automatski se računa broj vreća i obrnuto.",
        "boiler_power_kw" to "Snaga peći (kW)",
        "heating_area_m2" to "Grejna površina (m²)",
        "city_name" to "Naziv grada",
        "stock_quantity_pallets_bags" to "Količina na stanju (palete ili vreće)",
        "current_season_label" to "Tekuća sezona",
        "export_excel" to "Izvezi u Excel",
        "all_seasons" to "Sve sezone",
        "select_season" to "Odabir sezone",
        "no_entries_season" to "Nema unosa za odabranu sezonu.",
        "season_saved_hint" to "Statistika se računa od prvog unosa u ovoj sezoni."
    )

    private val sr = mapOf(
        "app_title" to "Peletko",
        "home" to "Početna",
        "back" to "Nazad",
        "refresh_temps" to "Osveži temperature",
        "daily_entry_btn" to "Unos dnevne potrošnje",
        "daily_entry_sub" to "Brzi dnevni unos",
        "history_stats_btn" to "Istorija / Statistika",
        "history_stats_sub" to "Metrike (kg/m², kg/kW, troškovi) i trendovi",
        "purchase_btn" to "Magacin/Kupovina",
        "purchase_sub" to "+ Nova nabavka",
        "inventory_title" to "Stanje zaliha",
        "remaining_bags" to "Preostalo: %s",
        "remaining_kg" to "Preostalo: %s kg",
        "days_left" to "Dovoljno za ~%s dana",
        "stock_depleted" to "Zalihe potrošene",
        "low_stock" to "Nisko!",
        "today_entered" to "Danas uneseno",
        "today_not_entered" to "Danas još nije uneseno",
        "today_prompt" to "Kliknite za brzi unos današnje potrošnje",
        "history_tab" to "Istorija",
        "stats_tab" to "Detaljna statistika",
        "save" to "Sačuvaj",
        "save_daily" to "Sačuvaj dnevni unos",
        "update_daily" to "Ažuriraj potrošnju",
        "bags" to "vreća",
        "bags_plural" to "vreće",
        "total_mass" to "Ukupna masa",
        "total_cost" to "Trošak",
        "outside_temp" to "Spoljna temperatura (°C)",
        "weather_auto_fetched" to "Automatski preuzeto sa interneta",
        "weather_fetching" to "Preuzimanje temperature sa interneta...",
        "notes" to "Kratka beleška (opciono)",
        "stock_negative_title" to "Nema dovoljno peleta na stanju",
        "stock_negative_msg" to "Ovaj unos prelazi trenutno stanje magacina. Preostalo bi bilo u minusu. Želite li ipak sačuvati unos?",
        "allow_negative_confirm" to "Dozvoli minus i sačuvaj",
        "cancel" to "Otkaži",
        "delete" to "Obriši",
        "settings" to "Podešavanja",
        "heating_area" to "Površina objekta (m²)",
        "boiler_power" to "Snaga kotla (kW)",
        "insulation" to "Izolacija objekta",
        "city" to "Grad / Klima zona",
        "brand" to "Proizvođač peleta",
        "theme" to "Tema aplikacije",
        "theme_system" to "Sistem",
        "theme_light" to "Svetla",
        "theme_dark" to "Tamna",
        "language" to "Jezik aplikacije",
        "currency" to "Valuta (Prikaz troškova)",
        "auto_weather_setting" to "Automatski preuzmi vremensku prognozu",
        "saved" to "Sačuvano",
        "updated" to "Ažurirano",
        "deleted" to "Obrisano",
        "purchase_saved" to "Zalihe uvećane",
        "kg_per_m2" to "kg / m² sezona",
        "kg_per_kw" to "kg / kW kotla",
        "cost_per_m2" to "po m²",
        "cost_per_day" to "po danu",
        "temp_vs_consumption" to "Prosečna temperatura/potrošnja peleta",
        "monthly_review" to "Mesečni pregled potrošnje",
        "total_recorded" to "Ukupno evidentirano",
        "no_entries_yet" to "Još nema unosa potrošnje",
        "no_entries_sub" to "Započnite dnevni unos klikom na početnom ekranu.",
        "delete_entry_confirm" to "Da li ste sigurni da želite da obrišete unos za datum %s (%s)?",
        "property_label" to "Objekat",
        "insulation_label" to "Izolacija",
        "kpi_title" to "Detalji o potrošnji",
        "specific_consumption" to "Specifična potrošnja",
        "boiler_load" to "Opterećenje snage",
        "cost_by_area" to "Trošak po površini",
        "daily_average" to "Dnevni prosek",
        "unit_per_day" to "dan",
        "unit_per_day_short" to "vr/dan",
        "sample_days_short" to "d.",
        "days_count_short" to "dana unosa",
        "temp_correlation_title" to "Korelacija grejanja i temperature",
        "no_data" to "Nema podataka",
        "temp_correlation_tip" to "💡 Savet: Uključeno automatsko preuzimanje temperature omogućava preciznu korelaciju bez ručnog unosa.",
        "no_monthly_data" to "Nema podataka za mesečni pregled.",
        "stock_overview" to "Pregled zaliha",
        "one_pallet_rule" to "1 paleta = 70 vreća",
        "remaining" to "Preostalo",
        "total_purchased" to "Ukupno kupljeno",
        "purchases_history" to "Istorija nabavki",
        "no_purchases" to "Nema unesenih nabavki",
        "add_purchase_prompt" to "Dodajte kupovinu peleta klikom na dugme ispod.",
        "pallets" to "paleta",
        "delete_purchase_confirm" to "Da li ste sigurni da želite da obrišete nabavku od %s paleta (%s)? Zalihe će biti umanjene.",
        "edit_purchase" to "Izmena nabavke",
        "edit" to "Izmeni",
        "purchase_updated" to "Nabavka ažurirana",
        "purchase_sheet_title" to "Unos nabavke u magacin",
        "purchase_sheet_info" to "1 paleta = tona = 70 vreća (1050 kg). Unosom paleta automatski se računa broj vreća i obrnuto.",
        "season" to "Sezona",
        "num_pallets" to "Broj paleta",
        "exact_bags" to "Tačan br. vreća",
        "price_per_pallet" to "Cena po paleti",
        "quantity" to "Količina",
        "supplier" to "Dobavljač / Proizvođač",
        "settings_sec1" to "Izgled i Lokalizacija",
        "settings_sec2" to "Lokacija i Pelet",
        "settings_sec3" to "Snaga kotla i grejna površina",
        "settings_sec4" to "Magacin i Nabavke",
        "pellet_class" to "Klasa peleta",
        "default_pallet_price" to "Podrazumevana cena palete",
        "allow_negative_title" to "Dozvoli unos kad nema zaliha",
        "allow_negative_sub" to "Upozori pre ulaska u negativno stanje",
        "about_app" to "O aplikaciji",
        "developer" to "Developer",
        "developer_name" to "ProleApps",
        "app_version" to "Verzija 1.2.0",
        "app_description" to "Jednostavno i precizno praćenje potrošnje peleta, stanja zaliha u magacinu i troškova grejanja uz automatsku vremensku prognozu.",
        "auto_temp_placeholder" to "Automatska temperatura...",
        "locked_temp_field" to "Zaključano polje (automatska temperatura)",
        "notes_placeholder" to "Npr. grejano 12 sati, vetrovito...",
        "supplier_placeholder" to "Npr. Kovan, Šišarka, Ensa, Medex...",
        "step_x_of_y" to "Korak %d od %d",
        "next" to "Dalje",
        "start_tracking" to "Započni praćenje",
        "initial_setup" to "Osnovno podešavanje",
        "onboarding_step1_title" to "Jezik, valuta i grad",
        "onboarding_step1_sub" to "Podesite jezik interfejsa, valutu za obračun troškova i vaš grad za automatsko preuzimanje temperatura.",
        "onboarding_step2_title" to "Snaga i kvadratura",
        "onboarding_step2_sub" to "Unesite snagu peći, grejnu površinu i izolaciju objekta za precizne industrijske proračune.",
        "onboarding_step3_title" to "Stanje magacina",
        "onboarding_step3_sub" to "1 paleta = 70 vreća (1050 kg). Unosom paleta automatski se računa broj vreća i obrnuto.",
        "boiler_power_kw" to "Snaga peći (kW)",
        "heating_area_m2" to "Grejna površina (m²)",
        "city_name" to "Naziv grada",
        "stock_quantity_pallets_bags" to "Količina na stanju (palete ili vreće)",
        "current_season_label" to "Tekuća sezona",
        "export_excel" to "Izvezi u Excel",
        "all_seasons" to "Sve sezone",
        "select_season" to "Odabir sezone",
        "no_entries_season" to "Nema unosa za odabranu sezonu.",
        "season_saved_hint" to "Statistika se računa od prvog unosa u ovoj sezoni."
    )

    private val hr = mapOf(
        "app_title" to "Peletko",
        "home" to "Početna",
        "back" to "Natrag",
        "refresh_temps" to "Osvježi temperature",
        "daily_entry_btn" to "Unos dnevne potrošnje",
        "daily_entry_sub" to "Brzi dnevni unos",
        "history_stats_btn" to "Povijest / Statistika",
        "history_stats_sub" to "Metrike (kg/m², kg/kW, troškovi) i trendovi",
        "purchase_btn" to "Magacin/Kupovina",
        "purchase_sub" to "+ Nova nabava",
        "inventory_title" to "Stanje zaliha",
        "remaining_bags" to "Preostalo: %s",
        "remaining_kg" to "Preostalo: %s kg",
        "days_left" to "Dovoljno za ~%s dana",
        "stock_depleted" to "Zalihe potrošene",
        "low_stock" to "Nisko!",
        "today_entered" to "Danas uneseno",
        "today_not_entered" to "Danas još nije uneseno",
        "today_prompt" to "Kliknite za brzi unos današnje potrošnje",
        "history_tab" to "Povijest",
        "stats_tab" to "Detaljna statistika",
        "save" to "Spremi",
        "save_daily" to "Spremi dnevni unos",
        "update_daily" to "Ažuriraj potrošnju",
        "bags" to "vreća",
        "bags_plural" to "vreće",
        "total_mass" to "Ukupna masa",
        "total_cost" to "Trošak",
        "outside_temp" to "Vanjska temperatura (°C)",
        "weather_auto_fetched" to "Automatski preuzeto s interneta",
        "weather_fetching" to "Dohvaćanje temperature s interneta...",
        "notes" to "Kratka bilješka (opcionalno)",
        "stock_negative_title" to "Nema dovoljno peleta na stanju",
        "stock_negative_msg" to "Ovaj unos prelazi trenutno stanje skladišta. Preostalo bi bilo u minusu. Želite li ipak spremiti unos?",
        "allow_negative_confirm" to "Dozvoli minus i spremi",
        "cancel" to "Odustani",
        "delete" to "Obriši",
        "settings" to "Postavke",
        "heating_area" to "Površina objekta (m²)",
        "boiler_power" to "Snaga peći (kW)",
        "insulation" to "Izolacija objekta",
        "city" to "Grad / Klima zona",
        "brand" to "Proizvođač peleta",
        "theme" to "Tema aplikacije",
        "theme_system" to "Sustav",
        "theme_light" to "Svijetla",
        "theme_dark" to "Tamna",
        "language" to "Jezik aplikacije",
        "currency" to "Valuta (Prikaz troškova)",
        "auto_weather_setting" to "Automatski dohvati vremensku prognozu",
        "saved" to "Spremljeno",
        "updated" to "Ažurirano",
        "deleted" to "Obrisano",
        "purchase_saved" to "Zalihe uvećane",
        "kg_per_m2" to "kg / m² sezona",
        "kg_per_kw" to "kg / kW peći",
        "cost_per_m2" to "po m²",
        "cost_per_day" to "po danu",
        "temp_vs_consumption" to "Prosječna temperatura/potrošnja peleta",
        "monthly_review" to "Mjesečni pregled potrošnje",
        "total_recorded" to "Ukupno evidentirano",
        "no_entries_yet" to "Još nema unosa potrošnje",
        "no_entries_sub" to "Započnite dnevni unos klikom na početnom zaslonu.",
        "delete_entry_confirm" to "Jeste li sigurni da želite obrisati unos za datum %s (%s)?",
        "property_label" to "Objekt",
        "insulation_label" to "Izolacija",
        "kpi_title" to "Detalji o potrošnji",
        "specific_consumption" to "Specifična potrošnja",
        "boiler_load" to "Opterećenje snage",
        "cost_by_area" to "Trošak po površini",
        "daily_average" to "Dnevni prosjek",
        "unit_per_day" to "dan",
        "unit_per_day_short" to "vr/dan",
        "sample_days_short" to "d.",
        "days_count_short" to "dana unosa",
        "temp_correlation_title" to "Korelacija grijanja i temperature",
        "no_data" to "Nema podataka",
        "temp_correlation_tip" to "💡 Savjet: Uključeno automatsko preuzimanje temperature omogućava preciznu korelaciju bez ručnog unosa.",
        "no_monthly_data" to "Nema podataka za mjesečni pregled.",
        "stock_overview" to "Pregled zaliha",
        "one_pallet_rule" to "1 paleta = 70 vreća",
        "remaining" to "Preostalo",
        "total_purchased" to "Ukupno kupljeno",
        "purchases_history" to "Povijest nabava",
        "no_purchases" to "Nema unesenih nabava",
        "add_purchase_prompt" to "Dodajte kupovinu peleta klikom na gumb ispod.",
        "pallets" to "paleta",
        "delete_purchase_confirm" to "Jeste li sigurni da želite obrisati nabavu od %s paleta (%s)? Zalihe će biti umanjene.",
        "edit_purchase" to "Uređivanje nabave",
        "edit" to "Uredi",
        "purchase_updated" to "Nabava ažurirana",
        "purchase_sheet_title" to "Unos nabave u skladište",
        "purchase_sheet_info" to "1 paleta = tona = 70 vreća (1050 kg). Unosom paleta automatski se računa broj vreća i obrnuto.",
        "season" to "Sezona",
        "num_pallets" to "Broj paleta",
        "exact_bags" to "Točan br. vreća",
        "price_per_pallet" to "Cijena po paleti",
        "quantity" to "Količina",
        "supplier" to "Dobavljač / Proizvođač",
        "settings_sec1" to "Izgled i Lokalizacija",
        "settings_sec2" to "Lokacija i Pelet",
        "settings_sec3" to "Snaga peći i grijana površina",
        "settings_sec4" to "Skladište i Nabave",
        "pellet_class" to "Klasa peleta",
        "default_pallet_price" to "Zadana cijena palete",
        "allow_negative_title" to "Dozvoli unos kad nema zaliha",
        "allow_negative_sub" to "Upozori prije ulaska u negativno stanje",
        "about_app" to "O aplikaciji",
        "developer" to "Developer",
        "developer_name" to "ProleApps",
        "app_version" to "Verzija 1.2.0",
        "app_description" to "Jednostavno i precizno praćenje potrošnje peleta, stanja zaliha u skladištu i troškova grijanja uz automatsku vremensku prognozu.",
        "auto_temp_placeholder" to "Automatska temperatura...",
        "locked_temp_field" to "Zaključano polje (automatska temperatura)",
        "notes_placeholder" to "Npr. grijano 12 sati, vjetrovito...",
        "supplier_placeholder" to "Npr. Kovan, Šišarka, Ensa, Medex...",
        "step_x_of_y" to "Korak %d od %d",
        "next" to "Dalje",
        "start_tracking" to "Započni praćenje",
        "initial_setup" to "Osnovno podešavanje",
        "onboarding_step1_title" to "Jezik, valuta i grad",
        "onboarding_step1_sub" to "Podesite jezik sučelja, valutu za obračun troškova i vaš grad za automatsko preuzimanje temperatura.",
        "onboarding_step2_title" to "Snaga i kvadratura",
        "onboarding_step2_sub" to "Unesite snagu peći, grijanu površinu i izolaciju objekta za precizne industrijske izračune.",
        "onboarding_step3_title" to "Stanje skladišta",
        "onboarding_step3_sub" to "1 paleta = 70 vreća (1050 kg). Unosom paleta automatski se računa broj vreća i obrnuto.",
        "boiler_power_kw" to "Snaga peći (kW)",
        "heating_area_m2" to "Grijana površina (m²)",
        "city_name" to "Naziv grada",
        "stock_quantity_pallets_bags" to "Količina na stanju (palete ili vreće)",
        "current_season_label" to "Tekuća sezona",
        "export_excel" to "Izvezi u Excel",
        "all_seasons" to "Sve sezone",
        "select_season" to "Odabir sezone",
        "no_entries_season" to "Nema unosa za odabranu sezonu.",
        "season_saved_hint" to "Statistika se računa od prvog unosa u ovoj sezoni."
    )

    private val en = mapOf(
        "app_title" to "Peletko",
        "home" to "Home",
        "back" to "Back",
        "refresh_temps" to "Refresh temperatures",
        "daily_entry_btn" to "Log Daily Consumption",
        "daily_entry_sub" to "Quick daily entry",
        "history_stats_btn" to "History / Statistics",
        "history_stats_sub" to "Metrics (kg/m², kg/kW, cost) & trends",
        "purchase_btn" to "Warehouse/Purchases",
        "purchase_sub" to "+ New purchase",
        "inventory_title" to "Current Inventory",
        "remaining_bags" to "Remaining: %s",
        "remaining_kg" to "Remaining: %s kg",
        "days_left" to "Enough for ~%s days",
        "stock_depleted" to "Stock depleted",
        "low_stock" to "Low!",
        "today_entered" to "Logged today",
        "today_not_entered" to "Not logged yet today",
        "today_prompt" to "Tap to quickly log today's consumption",
        "history_tab" to "History",
        "stats_tab" to "Detailed Statistics",
        "save" to "Save",
        "save_daily" to "Save Daily Entry",
        "update_daily" to "Update Entry",
        "bags" to "bag",
        "bags_plural" to "bags",
        "total_mass" to "Total Weight",
        "total_cost" to "Cost",
        "outside_temp" to "Outdoor Temperature (°C)",
        "weather_auto_fetched" to "Auto-fetched from internet",
        "weather_fetching" to "Fetching temperature from internet...",
        "notes" to "Short note (optional)",
        "stock_negative_title" to "Insufficient pellet inventory",
        "stock_negative_msg" to "This entry exceeds your warehouse stock. Stock would become negative. Do you still want to proceed?",
        "allow_negative_confirm" to "Allow negative & save",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "settings" to "Settings",
        "heating_area" to "Heated area (m²)",
        "boiler_power" to "Boiler power (kW)",
        "insulation" to "Building insulation",
        "city" to "City / Climate zone",
        "brand" to "Pellet manufacturer",
        "theme" to "App Theme",
        "theme_system" to "System",
        "theme_light" to "Light",
        "theme_dark" to "Dark",
        "language" to "App Language",
        "currency" to "Currency (Cost display)",
        "auto_weather_setting" to "Automatically fetch weather forecast",
        "saved" to "Saved",
        "updated" to "Updated",
        "deleted" to "Deleted",
        "purchase_saved" to "Inventory increased",
        "kg_per_m2" to "kg / m² season",
        "kg_per_kw" to "kg / kW boiler",
        "cost_per_m2" to "per m²",
        "cost_per_day" to "per day",
        "temp_vs_consumption" to "Average Temperature / Pellet Consumption",
        "monthly_review" to "Monthly Consumption Summary",
        "total_recorded" to "Total Recorded",
        "no_entries_yet" to "No consumption entries yet",
        "no_entries_sub" to "Start logging daily consumption on the home screen.",
        "delete_entry_confirm" to "Are you sure you want to delete the entry for %s (%s)?",
        "property_label" to "Property",
        "insulation_label" to "Insulation",
        "kpi_title" to "Consumption Details",
        "specific_consumption" to "Specific consumption",
        "boiler_load" to "Boiler load",
        "cost_by_area" to "Cost per area",
        "daily_average" to "Daily average",
        "unit_per_day" to "day",
        "unit_per_day_short" to "bags/day",
        "sample_days_short" to "d.",
        "days_count_short" to "days logged",
        "temp_correlation_title" to "Heating & Temperature Correlation",
        "no_data" to "No data",
        "temp_correlation_tip" to "💡 Tip: Automatic weather fetching enables accurate correlation without manual entry.",
        "no_monthly_data" to "No data available for monthly overview.",
        "stock_overview" to "Stock Overview",
        "one_pallet_rule" to "1 pallet = 70 bags",
        "remaining" to "Remaining",
        "total_purchased" to "Total Purchased",
        "purchases_history" to "Purchase History",
        "no_purchases" to "No purchases recorded",
        "add_purchase_prompt" to "Add pellet purchases by clicking the button below.",
        "pallets" to "pallets",
        "delete_purchase_confirm" to "Are you sure you want to delete the purchase of %s pallets (%s)? Inventory will be reduced.",
        "edit_purchase" to "Edit Purchase",
        "edit" to "Edit",
        "purchase_updated" to "Purchase updated",
        "purchase_sheet_title" to "Add Warehouse Purchase",
        "purchase_sheet_info" to "1 pallet = 70 bags (1050 kg). Entering pallets automatically calculates the number of bags and vice versa.",
        "season" to "Season",
        "num_pallets" to "Number of pallets",
        "exact_bags" to "Exact bag count",
        "price_per_pallet" to "Price per pallet",
        "quantity" to "Quantity",
        "supplier" to "Supplier / Brand",
        "settings_sec1" to "Appearance & Localization",
        "settings_sec2" to "Location & Pellet",
        "settings_sec3" to "Boiler Power & Heated Area",
        "settings_sec4" to "Inventory & Purchases",
        "pellet_class" to "Pellet Class",
        "default_pallet_price" to "Default pallet price",
        "allow_negative_title" to "Allow entry when out of stock",
        "allow_negative_sub" to "Warn before stock becomes negative",
        "about_app" to "About App",
        "developer" to "Developer",
        "developer_name" to "ProleApps",
        "app_version" to "Version 1.2.0",
        "app_description" to "Simple and accurate tracking of pellet consumption, warehouse inventory, and heating costs with automated weather forecasting.",
        "auto_temp_placeholder" to "Auto weather temperature...",
        "locked_temp_field" to "Locked field (auto weather temperature)",
        "notes_placeholder" to "e.g. heated 12 hours, windy...",
        "supplier_placeholder" to "e.g. Timber, Medex, Premium...",
        "step_x_of_y" to "Step %d of %d",
        "next" to "Next",
        "start_tracking" to "Start tracking",
        "initial_setup" to "Initial Setup",
        "onboarding_step1_title" to "Language, currency & city",
        "onboarding_step1_sub" to "Configure app language, cost currency, and your city for automatic weather updates.",
        "onboarding_step2_title" to "Boiler power & area",
        "onboarding_step2_sub" to "Enter boiler power, heated area, and building insulation for accurate industrial metrics.",
        "onboarding_step3_title" to "Warehouse inventory",
        "onboarding_step3_sub" to "1 pallet = 70 bags (1050 kg). Entering pallets automatically calculates bag count and vice versa.",
        "boiler_power_kw" to "Boiler power (kW)",
        "heating_area_m2" to "Heated area (m²)",
        "city_name" to "City name",
        "stock_quantity_pallets_bags" to "Current stock (pallets or bags)",
        "current_season_label" to "Current season",
        "export_excel" to "Export to Excel",
        "all_seasons" to "All seasons",
        "select_season" to "Select season",
        "no_entries_season" to "No entries for the selected season.",
        "season_saved_hint" to "Statistics are calculated from your first entry in this season."
    )
}
